### ISSUE TITLE
All bands shown on dashboard

### ISSUE THREAD

**Issue by Shpigford** [Rockburg/rockburg#101]
@nathanpalmer Looks like something is up with the policy scope for the Managers dashboard as I'm seeing _all_ bands, even ones that aren't mine.

https://alpha.rockburg.com/dashboard

<img width="1204" alt="screen shot 2019-01-13 at 10 57 06 am" src="https://user-images.githubusercontent.com/35243/51088162-1464fb80-1722-11e9-8dd3-29731e7eb632.png">

**Comment by Shpigford** [comment]
Specifically, this line seems to be problematic...

`@bands = policy_scope(Band).all`

I don't know enough of how Pundit works yet to grasp how that works, but right now that looks like it calls all bands when it needs to just be the `current_manager`'s bands.

**Comment by nathanpalmer** [comment]
This has been addressed in #102
