### ISSUE TITLE
use NES.css?

### ISSUE THREAD

**Issue by evexoio** [Rockburg/rockburg#110]
I'm a maintainer of [NES.css](https://nostalgic-css.github.io/NES.css/),

and since this is a game, I think NES.css can be of some help if we want to make this look more like a game.

I'm opening this to discuss if we should implement NES.css here

**Comment by Shpigford** [comment]
Looks really cool!

Not really going for the old-school 8-bit look on this, but I do like the idea of having a framework in place for the UI.
