### ISSUE TITLE
ActiveRecord::RangeError: PG::NumericValueOutOfRange: ERROR:  integer out of range

### ISSUE THREAD

**Issue by Shpigford** [Rockburg/rockburg#24]
https://sentry.io/rockburg/rockburg/issues/527078212/

```
PG::NumericValueOutOfRange: ERROR:  integer out of range

  app/workers/activity_worker.rb:81:in `perform'
    @band.increment!(:buzz, new_buzz)
...
(47 additional frame(s) were not displayed)

ActiveRecord::RangeError: PG::NumericValueOutOfRange: ERROR:  integer out of range
: UPDATE "bands" SET "buzz" = COALESCE("buzz", 0) + 13855257760 WHERE "bands"."id" = $1

PG::NumericValueOutOfRange: ERROR:  integer out of range
: UPDATE "bands" SET "buzz" = COALESCE("buzz", 0) + 13855257760 WHERE "bands"."id" = $1
```

**Comment by delynn** [comment]
This is just a cursory inspection, but the attendance calculation on line 69 looks like it could result in a number that's larger than the capacity of the venue. On line 75 if `attendance / cap` then ends up being a large whole number, I believe that could result in `new_buzz` being larger than the limit of Postgres integer column type?

**Comment by Shpigford** [comment]
@delynn Yeah, seemed to be a limit of the column type. Changed to a `bigint` which should solve the issue.
