### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by Shpigford** [Rockburg/rockburg#3]
Bless my heart, not a single test exists for any of this. Any tests of any sort would be welcome.

**Comment by ryanckulp** [comment]
you OK w/ rspec? happy to begin setting up a suite.

**Comment by Shpigford** [comment]
@ryanckulp Yep, sounds great.

**Comment by Shpigford** [comment]
@ryanckulp FYI, @bsharpe just did a PR that may be of interest as you work on tests as well: https://github.com/Rockburg/rockburg/pull/23

**Comment by ryanckulp** [comment]
understood, will work from that, thanks @bsharpe !

**Comment by nathanpalmer** [comment]
Alright, so I've set up quite a few tests here for each controller and the policies. Though the controller tests are simply a single happy-path test to ensure the access was granted. I'd be happy to jump into a few other assertions to get the coverage percentage a little higher if you want to assign me to this one.

**Comment by Shpigford** [comment]
I think this is a solid start, at least enough to close this specific issue (as it's quite ambiguous).
