### ISSUE TITLE
New fans increased by more than the number of people attending, no one buying my recordings

### ISSUE THREAD

**Issue by shobhitic** [Rockburg/rockburg#36]
Since the past few gigs that I've been playing, I am making new fans like crazy. I am getting roughly double the number of new fans as compared to people at my gig. Is this a bug?

<img width="490" alt="screen shot 2018-04-14 at 12 36 18 am" src="https://user-images.githubusercontent.com/2300751/38753450-18f1c864-3f7c-11e8-8183-ca3db805dca2.png">

Another thing (which I realized after playing a bit more), I released a song, and despite have 3.9M fans, I sold only worth $1.

<img width="590" alt="screen shot 2018-04-14 at 12 46 19 am" src="https://user-images.githubusercontent.com/2300751/38753934-9d0182ba-3f7d-11e8-96dc-e03487a3c2f3.png">

This is surely a bug.

**Comment by Shpigford** [comment]
There's definitely an issue with the way we're calculating gig attendance (see #22). So the first part of your issue would be related to that.

As for only $1...sounds like that is indeed a bug. If you wouldn't mind either posting a new issue specific to that or just split this issue up.

**Comment by shobhitic** [comment]
I'll create a new issue for that.

Meanwhile, I have been able to get more fans than people on earth 😄 

<img width="1203" alt="screen shot 2018-04-14 at 1 01 28 am" src="https://user-images.githubusercontent.com/2300751/38754456-921065fe-3f7f-11e8-921e-bdbe33714b29.png">

**Comment by Shpigford** [comment]
Hahaha, and they say Rock is dead.

**Comment by pnomolos** [comment]
> Hahaha, and they say Rock is dead

[Lots](https://en.wikipedia.org/wiki/Heraldine_Rock). [of](https://en.wikipedia.org/wiki/John_Rock_(abolitionist)). [Rocks](https://en.wikipedia.org/wiki/John_Rock_(American_scientist)). [are](https://en.wikipedia.org/wiki/Joseph_Rock). [dead](https://en.wikipedia.org/wiki/Claude_Rock).

... sorry, I had to :laughing:

**Comment by Shpigford** [comment]
I believe this has all been fixed with recent updates.
