### ISSUE TITLE
Apply real-ish world data to genre popularity

### ISSUE THREAD

**Issue by Shpigford** [Rockburg/rockburg#39]
Wonder if there's a way to derive fan sentiment for genres from real-world data, like... surely the potential fanbase for an Big Band Orchestra is smaller than for a Boy Band.

**Comment by ryanckulp** [comment]
i dig it. found this:
https://blog.rapidapi.com/2017/09/16/top-four-free-music-data-apis/

see `#2, lastFM`... free API key, can be used to fetch top artists. what if we fetch ~weekly, loop each artist and sum their genre(s) to achieve this pulse/sentiment?

output of this service object would "math" against some fan multiplier, and boom we have overall interest parity with the real world.

happy to take a crack
