### ISSUE TITLE
Implement record ownership validation

### ISSUE THREAD

**Issue by Shpigford** [Rockburg/rockburg#4]
There's currently no validation for editing items under a given manager (meaning you could go and edit and take action on other manager's bands).

Need to add validation around that.

**Comment by ryanckulp** [comment]
knocking this out now

**Comment by shobhitic** [comment]
Is this still open?

**Comment by Shpigford** [comment]
@shobhitic It is indeed still open.

**Comment by ryanckulp** [comment]
sorry, missed this specific request.

@shobhitic this same jam should work:
https://github.com/Rockburg/rockburg/pull/54/files

**Comment by nathanpalmer** [comment]
PR #91 should take care of this one. I don't have access to assign myself to it though and change the status.

**Comment by Shpigford** [comment]
Fixed with #91.

**Comment by nathanpalmer** [comment]
Looks like this needs to be moved to "Done" in the Launch project.
