### ISSUE TITLE
Build maintenance script to reset game

### ISSUE THREAD

**Issue by Shpigford** [Rockburg/rockburg#43]
There needs to be a way to reset the game while keeping Manager profiles.

The main thing is all managers would start back with 50,000 in money.

**Comment by bsharpe** [comment]
And no bands? no recordings? no songs? no gigs?

**Comment by Shpigford** [comment]
@bsharpe Correct. Basically reset the database and re-seed it. Only difference between a full database reset would be keeping the Manager profiles and giving them a starting balance of 50,000.

**Comment by bsharpe** [comment]
#57
