### ISSUE TITLE
Manager balance sorting incorrect

### ISSUE THREAD

**Issue by Shpigford** [Rockburg/rockburg#50]
https://alpha.rockburg.com/charts/managers

The sorting of managers by balance doesn't appear to be working correctly.

<img width="794" alt="cloudapp annotation 2018-04-15 at 5 39 52 pm png" src="https://user-images.githubusercontent.com/35243/38784194-10ca45ea-40d4-11e8-9776-baebab97ed16.png">

@bsharpe I believe this was something you were working on?

**Comment by bsharpe** [comment]
yep -- was trying to do it in the DB instead of Ruby -- which is why i brought up the difficulty of doing this list when the balance lives on a `has_many` relationship

**Comment by bsharpe** [comment]
PR #52
