### ISSUE TITLE
Reworking Song-to-Release cycle

### ISSUE THREAD

**Issue by Shpigford** [Rockburg/rockburg#92]
I've been rethinking the way the Song-to-Release cycle works. Right now it's very clunky and the activities associated with it seem overly complicated. There's no reason to write a song, then record a song, then record multiple songs again to record an album and then release it.

Instead, I'm proposing the cycle move like so...

1. Write a song
2. Record a written song
3. Release a song or multiple songs (as an album)

Ultimately "releases" are just a method of distributing and packaging recordings as Singles, EPs or LPs.

With that in mind, the database scheme needs to be reworked, which I think also drastically simplifies it.

So, that overview follows. Let me know of anything I'm potentially missing.

# SONGS
* The base unit of an item that a band can create

```
## schema ##
band_id
name
quality
status
created_at
updated_at
```

# RECORDINGS
* Chosen from written SONGS
* Has a "quality" component based on chosen studio

```
## schema ##
band_id
studio_id
song_id
quality
created_at
updated_at
```

# RELEASES
* Chosen from RECORDINGS
* Named
* Money is made from streams & sales of releases

```
## schema ##
band_id
name
kind (single, ep, lp)
created_at
updated_at
```

# RECORDINGS_RELEASES
* has_and_belongs_to_many

```
## schema ##
recording_id
release_id

```

# STREAMS
* Daily update on # of streams of a given release

```
## schema ##
band_id
release_id
num_streams
created_at
updated_at
```

**Comment by nathanpalmer** [comment]
I assume there is still a relationship between songs and recordings like there is today? When I first saw recording I had assumed that it had a direct relationship to a song. So you would:

1. Write a song (create `song`)
2. Record a song (create `recording`, belongs_to `song`)
3. Release an album (create `release`, has_many `recordings`)

What does it mean for a recording to have many songs? Are you referring to a recording session.. as in studio time? I'd consider the studio along with the corresponding activity enough to note that part.

**Comment by nathanpalmer** [comment]
Ah, so, what happens if you have a new recording? Does the quality update on the original recording row? and what is stored on the individual song_recordings rows?

I would think it would be straight-forward to create additional recording objects if a new recording is made. Then each song + studio can maintain its own quality rating and can be included on a release (or a re-recording and then a later re-release.)

For example:

```
Band (1) - The Beatles
Song (1) - Let It Be

Studio(1) - EMI
Studio(2) - Trident Studios

Recording (1): Song (1), Studio (1)
Recording (2): Song (1), Studio (2)
```

**Comment by Shpigford** [comment]
Ah, sorry, there's no song_recordings table or anything.

song has_many recordings
recordings belongs_to song

Each recording creates a new line in Recordings that references back to the original song. But each Recording is standalone.

**Comment by nathanpalmer** [comment]
Perfect. That's exactly what I was going for. So I'd add a `song_id` to your pseudo schema up above on recording to show that relationship.
